[env:esp32-s3-n16r8v]

platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

# Configurações de Memória e Flash
board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_upload.flash_size = 16MB

# Velocidades
monitor_speed = 115200
upload_speed = 921600

# ----------------------------------------------------
# BIBLIOTECAS (Faca na Web e JSON!)
# ----------------------------------------------------
lib_deps = 
    # Vazio! O controle do Aero 2 usará apenas bibliotecas nativas (FreeRTOS, Wire, etc.)

# ----------------------------------------------------
# FLAGS DE COMPILAÇÃO
# ----------------------------------------------------
build_flags = 
    # PSRAM otimizado
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCONFIG_SPIRAM_USE_CAPS_ALLOC=1
    -DCONFIG_SPIRAM_USE_MALLOC=1
    
    # Otimizações de CPU 
    -DCONFIG_ESP32S3_DEFAULT_CPU_FREQ_240=1
    -DCONFIG_ESP32S3_DEFAULT_CPU_FREQ_MHZ=240
    
    # Otimizações de compilação
    -O3
    -DCORE_DEBUG_LEVEL=1
    
    # Desabilitar rádios para evitar interrupções no processador e economizar energia
    -DCONFIG_BT_ENABLED=0
    -DCONFIG_ESP32_WIFI_ENABLED=0